[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["../.devkit/contracts/lib"]
remappings = [
    "forge-std/=../.devkit/contracts/lib/forge-std/src/",
    "@eigenlayer-middleware/=../.devkit/contracts/lib/eigenlayer-middleware/",
    "@eigenlayer-contracts/=../.devkit/contracts/lib/eigenlayer-middleware/lib/eigenlayer-contracts/",
    "@openzeppelin/=../.devkit/contracts/lib/eigenlayer-middleware/lib/openzeppelin-contracts/",
    "@openzeppelin-upgrades/=../.devkit/contracts/lib/eigenlayer-middleware/lib/openzeppelin-contracts-upgradeable/",
    "@project/=src/"
]
solc_version = "0.8.27"
optimizer = true
optimizer_runs = 200
via_ir = false

[fmt]
line_length = 120
tab_width = 4

