version: 0.0.3
config:
  project:
    name: eigenmatch-avs
    version: 0.1.0
    context: eigenmatch
    telemetry_enabled: false
    templateBaseUrl: https://github.com/Layr-Labs/hourglass-avs-template
    templateVersion: v0.0.10

